source_language: English
target_language: Arabic
model: gpt-4o
secondary_model: gpt-3.5-turbo
task: cultural_translation
storage_folder_path: ./ResultsCultural
data_path: ./Data/DestructuredData/arabic_data_destructured.csv